In [1]:
import numpy as np
import pandas
import nltk

In [2]:
import glob #list .txt file
pos_list=glob.glob("data\\movie-reviews-en\\train\\pos\\*.txt")
neg_list=glob.glob("data\\movie-reviews-en\\train\\neg\\*.txt")

In [3]:
#On crée un text contenant toutes les phrases, afin de compter les occurences de chaque ;ot
#Peut être pas la bonne maniere de faire, peut etre faire un decompte pour chaque phrase 
#et apres faire une moyenne d'ocurrence pour chaque mot

full_text = ''

for file in pos_list:
    f = open(file, "r")
    full_text += f.read()

for file in neg_list:
    f = open(file, "r")
    full_text += f.read()
    

In [4]:
import string
#On supprime la ponctuation et retour de ligne
full_text = full_text.translate(str.maketrans('', '', string.punctuation)).replace('\n','')

In [5]:
from collections import Counter
#On compte le nombre d'apparition de chaque mot
count = Counter(full_text.split())

In [6]:
len(count) #Nb de mots

45241

In [7]:
most_common = count.most_common(200)
most_common[0:8]

[('the', 68395),
 ('a', 34165),
 ('and', 31648),
 ('of', 30420),
 ('to', 28507),
 ('is', 22511),
 ('in', 19417),
 ('that', 13541)]

In [8]:
n = len(pos_list)
data_pos = np.zeros((n,200))

for file,i in zip(pos_list,range(n)):
    f = open(file, "r")
    text = f.read()
    
    for j in range(0,200):
        if most_common[j][0] in text:
            data_pos[i][j]=1


In [9]:
data_pos

array([[1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 1., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       ...,
       [1., 1., 1., ..., 1., 0., 1.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 1., 0.]])

In [10]:
n = len(neg_list)
data_neg = np.zeros((n,200))

for file,i in zip(neg_list,range(n)):
    f = open(file, "r")
    text = f.read()
    
    for j in range(0,200):
        if most_common[j][0] in text:
            data_neg[i][j]=1


In [11]:
data_neg

array([[1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 1., 0., 0.],
       [1., 1., 1., ..., 1., 1., 0.],
       ...,
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 1., 1.]])

## Tentative de Bayes Naif

P(POS) = P(NEG) = 1/2

In [12]:
p_w_pos = np.sum(data_pos,axis=0)/900 #P(Word|POS)
p_w_neg = np.sum(data_neg,axis=0)/900 #P(Word|NEG)

In [13]:
p_w = (np.sum(data_pos,axis=0)+np.sum(data_neg,axis=0))/1800 #P(Word)

In [14]:
p_w_pos.shape

(200,)

In [15]:
f = open('data\\movie-reviews-en\\test\\pos\\cv900_10331.txt', "r")
text_pos = f.read() #Ouverture d'un text pour test

In [16]:
text_pos = text_pos.translate(str.maketrans('', '', string.punctuation)).replace('\n','')

In [17]:
text_input = np.zeros((200))
for j in range(0,200):
        if most_common[j][0] in text_pos:
            text_input[j]=1

In [18]:
text_input

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1.,
       1., 0., 1., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0., 1., 0.,
       0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1.,
       0., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1.,
       1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0.])

In [19]:
text_input.shape

(200,)

In [20]:
s=1
for i in range(200):
    if text_input[i]==1:
        s=s*p_w_pos[i]        #Produit P(W|POS)

In [21]:
s 

7.188481433242468e-26

In [22]:
s*0.5  #Produit P(W|POS) * P(POS)

3.594240716621234e-26

In [23]:
s2=1
for i in range(200):
    if text_input[i]==1:
        s2=s2*p_w[i] #Produit P(W)

In [24]:
s2 

9.85186501803198e-27

In [25]:
(s*0.5)/s2  #Produit P(W|POS) * P(POS) / P(W)

3.6482845735732825